### ISSUE TITLE
Search Questions

### ISSUE THREAD

**Issue by jpe442** [jpe442/agora#7]
- [x] backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducers
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jpe442** [comment]
add details here

**Comment by mladenoff** [comment]
Since this just makes the search results appear on the same page (rather than a whole new component loading up) consider refactoring into a live search before you put this in your portfolio

**Comment by mladenoff** [comment]
lgtm
